---
title: The Learning Lab
description: A New Learning Initiative in UNC-CH's Department of Computer Science
theme: jekyll-theme-cayman
datatable: true
google_analytics: UA-148497617-1
show_downloads: true
---
